baseURL = 'https://hugo-asciidoc-blog.netlify.app/'
languageCode = 'en-us'
title = 'My Blog using Hugo & Asciidoc'
theme = "ananke"

[params]
    custom_css = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css", "adoc.css"]

[markup]
    [markup.asciidocExt]
        [markup.asciidocExt.attributes]
            allow-uri-read = ""
            source-highlighter = "rouge"
            rouge-css = "style"
            rouge-style = "thankful_eyes"
            imagesdir = "/images"
            icons = "font"

[security.exec]
    allow = ['^asciidoctor$']

[security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
